/Users/kelseydoerksen/opt/anaconda3/envs/sudsaq-uq/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py:126: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.
  warnings.warn(
Grabbing training data...
Grabbing testing data...
Training lower bound model...
Training EPOCH 0:
Training upper bound model...
Training EPOCH 0:
Predicting lower bounds...
test set loss is: 1.7319480180740356
Predicting upper bounds...
test set loss is: 15.849461555480957
Quantile Regression Coverage without conformal is: 0.00015318627450977562
Predicting lower bounds on calibration set...
test set loss is: 2.095101833343506
Predicting upper bounds on calibration set...
Traceback (most recent call last):
  File "/Users/kelseydoerksen/code/sudsaq-kelsey-research/research/kelsey/unet/run_pipeline.py", line 131, in <module>
    run_cqr(unet, device, aq_train_dataset, aq_test_dataset, save_dir, experiment, 0.1, args.channels,
  File "/Users/kelseydoerksen/code/sudsaq-kelsey-research/research/kelsey/unet/run_cqr.py", line 268, in run_cqr
    qyhat = calibrate_qyhat(cal_loader, uncal_lower_preds_c, uncal_upper_preds_c, alpha)
  File "/Users/kelseydoerksen/code/sudsaq-kelsey-research/research/kelsey/unet/run_cqr.py", line 196, in calibrate_qyhat
    s = np.amax([np.array(lower) - np.array(y_true), np.array(y_true) - np.array(upper)], axis=0)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (16,) + inhomogeneous part.
test set loss is: 2.0953400135040283
Calculating qyhat for calibration...